// Test-infrastructure suite (M0-TEST-01): the seed-handling convention
// for randomized tests (docs/testing.md §4).
//
// Step Verify scope (roadmap/M0-foundations.md):
//   - a seeded random test passes identically on two CI runs — this suite
//     pins a known-answer FNV-1a hash of a fixed draw count under the
//     default seed (and under a LAIGE_TEST_SEED override) and prints a
//     machine-greppable `test-seed-check` line per run, so two CI runs of
//     the same commit show identical lines in the job logs and the
//     archived Testing/Temporary/LastTest.log;
//   - the fixed default seed is overridable (LAIGE_TEST_SEED env var) and
//     identical to laige-fuzz's default (one documented repo-wide seed).
//
// House conventions: the FNV-1a 64-bit convention is the same as the
// prng_tests and math_fixed_tests KATs (big-endian bytes per u64 —
// endianness-independent); named constants throughout (CORE-005);
// KAT constants below were generated by running this suite and pinning
// the printed values — a change here means the algorithm or the seed
// changed, which is loud by design (ARCH-010).
//
// NFR-8.10 policy self-checks: this TU must build with exceptions and
// RTTI disabled (laige_apply_engine_policy, see tests/testing/CMakeLists.txt).

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <string>

#include "gtest/gtest.h"
// gtest-spi.h is GoogleTest's documented testing-support header (used by
// GoogleTest's own suite): EXPECT_NONFATAL_FAILURE lets this suite assert
// the loud-failure path of TestSeed() without the test failing itself.
#include "gtest/gtest-spi.h"
#include "laige/prng.h"
#include "laige_test_seed.h"

#if defined(__cpp_exceptions)
static_assert(false,
              "seeded_random_tests must be built with exceptions disabled "
              "(NFR-8.10); see laige_apply_engine_policy().");
#elif defined(__EXCEPTIONS) && __EXCEPTIONS
static_assert(false,
              "seeded_random_tests must be built with exceptions disabled "
              "(NFR-8.10); see laige_apply_engine_policy().");
#endif

#if defined(__cpp_rtti) && __cpp_rtti
static_assert(false,
              "seeded_random_tests must be built with RTTI disabled "
              "(NFR-8.10); see laige_apply_engine_policy().");
#endif

namespace {

using u32 = std::uint32_t;
using u64 = std::uint64_t;

// Fixed draw count for the known-answer hashes (named: CORE-005).
constexpr u32 kSeedCheckDraws = 65536;

// Substream ids: stable test identities (docs/testing.md §4). Each id is
// owned by exactly one suite/file so substreams never collide.
constexpr u32 kSeedCheckStreamId = 0x0001;   // this suite's default-seed KAT
constexpr u32 kOverrideStreamId = 0x0002;    // this suite's override-seed KAT

// The override seed for the env-var test: named, different from
// kDefaultTestSeed, so a broken env read cannot accidentally pass.
constexpr u64 kOverrideSeed = 0x2468ACCE01234567ull;

// First 8 draws of the default-seed, stream-1 substream (KAT): a fast
// failure diagnostic next to the full-stream hash.
constexpr u64 kFirstDrawsStream1[8] = {
    0x0EE1EED94C2CAA69ull, 0x4D64B354EA0FFF1Full, 0x9343A884890B5222ull,
    0xEDE0A379387022A6ull, 0x98A115D856F6A2BAull, 0xDF66706092CBE9C4ull,
    0x5DC877208B35398Full, 0x4F83FA225F6E1A7Cull,
};

// Full-stream KATs (65536 draws each, FNV-1a 64-bit over big-endian bytes
// per draw): identical on every build, compiler, and CI run.
constexpr u64 kKnownAnswerDefaultSeed = 0x7EA4049545656830ull;
constexpr u64 kKnownAnswerOverrideSeed = 0x535D2CA741B61CBFull;

// FNV-1a 64-bit, big-endian byte order per u64 (the same convention as
// prng_tests / math_fixed_tests KATs — endianness-independent).
u64 fnv1a64(const u64* values, std::size_t n) {
  u64 h = 0xcbf29ce484222325ull;  // FNV offset basis (named: FNV-1a spec)
  for (std::size_t i = 0; i < n; ++i) {
    for (int shift = 56; shift >= 0; shift -= 8) {
      h ^= (values[i] >> shift) & 0xFFull;
      h *= 0x100000001b3ull;  // FNV prime (named: FNV-1a spec)
    }
  }
  return h;
}

// Draw kSeedCheckDraws values from the substream of `seed` and print the
// machine-greppable identity line (LOG-001) BEFORE asserting, so the line
// reaches the ctest output and the CI job logs even when the KAT
// mismatches. Two CI runs of the same commit must print identical lines
// (M0-TEST-01 Verify).
u64 seedCheck(u64 seed, u32 streamId, const char* label) {
  laige::Prng rng = laige::Prng::deriveSubstream(seed, streamId);
  u64 hash = 0xcbf29ce484222325ull;
  u64 draw;
  for (u32 i = 0; i < kSeedCheckDraws; ++i) {
    draw = rng.next_u64();
    for (int shift = 56; shift >= 0; shift -= 8) {
      hash ^= (draw >> shift) & 0xFFull;
      hash *= 0x100000001b3ull;
    }
  }
  std::printf("test-seed-check %s seed=0x%016llx stream=%u draws=%u "
              "fnv1a=0x%016llx\n",
              label, static_cast<unsigned long long>(seed), streamId,
              kSeedCheckDraws, static_cast<unsigned long long>(hash));
  std::fflush(stdout);
  return hash;
}

// RAII around LAIGE_TEST_SEED: the override test sets it for the duration
// of the test body and restores the prior state (absent or present) even
// on failure. Platform boundary (CPP-009): setenv/unsetenv are C99/POSIX;
// MSVC's CRT does not provide them, so the Windows branch uses _putenv_s
// (the documented secure variant — no C4996 under /WX). On Windows,
// _putenv_s(name, "") is the "unset" equivalent: TestSeed() treats an
// empty value exactly as unset (the same lookup outcome ReadEnvVar gives
// on POSIX, where unsetenv removes the variable outright).
class ScopedTestSeedEnv {
 public:
  explicit ScopedTestSeedEnv(const char* value) {
    priorValue_ = laige::testing::ReadEnvVar(laige::testing::kTestSeedEnvVar);
    hadPrior_ = !priorValue_.empty();
    SetVar(laige::testing::kTestSeedEnvVar, value);
  }
  ~ScopedTestSeedEnv() {
    SetVar(laige::testing::kTestSeedEnvVar,
           hadPrior_ ? priorValue_.c_str() : "");
  }

 private:
  static void SetVar(const char* name, const char* value) {
#if defined(_MSC_VER)
    ::_putenv_s(name, value);
#else
    if (value == nullptr || value[0] == '\0') {
      ::unsetenv(name);
    } else {
      ::setenv(name, value, 1);
    }
#endif
  }

  bool hadPrior_ = false;
  std::string priorValue_;
};

}  // namespace

// ---------------------------------------------------------------------------
// SeededRandom — the seed-handling convention (M0-TEST-01)
// ---------------------------------------------------------------------------

// The default-seed known answer: 65536 draws from the documented default
// seed's stream-1 substream. Identical on every build, compiler, and CI
// run (pure integer arithmetic, ARCH-010).
TEST(SeededRandom, DefaultSeedKnownAnswer) {
  const u64 hash = seedCheck(laige::testing::kDefaultTestSeed,
                             kSeedCheckStreamId, "default");
  EXPECT_EQ(kKnownAnswerDefaultSeed, hash)
      << "default-seed stream changed (seed 0x1F055EED, stream "
      << kSeedCheckStreamId << ", " << kSeedCheckDraws << " draws); see the "
         "test-seed-check line above — re-pin the KAT only with a "
         "documented algorithm/seed change (docs/testing.md §4)";
  // Fast diagnostic: the first draws of the same stream.
  laige::Prng rng =
      laige::Prng::deriveSubstream(laige::testing::kDefaultTestSeed,
                                   kSeedCheckStreamId);
  for (int i = 0; i < 8; ++i) {
    EXPECT_EQ(kFirstDrawsStream1[i], rng.next_u64()) << "draw " << i;
  }
}

// One documented default seed repo-wide: the test default equals
// laige-fuzz's default (tools/fuzz/laige-fuzz.cpp kDefaultSeed).
TEST(SeededRandom, DefaultSeedMatchesTheFuzzRunnerSeed) {
  EXPECT_EQ(0x1F055EEDull, laige::testing::kDefaultTestSeed);
}

// The override path: LAIGE_TEST_SEED replaces the default, TestSeed()
// reports it, and the override-seed stream has its own committed KAT.
TEST(SeededRandom, SeedOverrideFromEnv) {
  ScopedTestSeedEnv scope(std::to_string(kOverrideSeed).c_str());
  // Decimal form, the accepted alternative to 0x-hex.
  EXPECT_EQ(kOverrideSeed, laige::testing::TestSeed());
  const u64 hash =
      seedCheck(kOverrideSeed, kOverrideStreamId, "override");
  EXPECT_EQ(kKnownAnswerOverrideSeed, hash)
      << "override-seed stream changed (seed 0x2468ACCE01234567, stream "
      << kOverrideStreamId << ", " << kSeedCheckDraws << " draws); see the "
         "test-seed-check line above";
}

// The invalid-env path of TestSeed(): a set-but-unparseable LAIGE_TEST_SEED
// records a loud failure with the offending value (CORE-008) and falls
// back to the default seed so the caller can complete its assertions.
TEST(SeededRandom, InvalidSeedEnvFailsLoudly) {
  ScopedTestSeedEnv scope("not-a-seed");
  u64 seed = 0;
  EXPECT_NONFATAL_FAILURE({ seed = laige::testing::TestSeed(); },
                          "LAIGE_TEST_SEED='not-a-seed' is not a valid seed");
  EXPECT_EQ(laige::testing::kDefaultTestSeed, seed);
}

// The seed parser accepts the documented forms and rejects the rest.
TEST(SeededRandom, SeedParserAcceptsDocumentedFormsOnly) {
  u64 v = 0;
  EXPECT_TRUE(laige::testing::ParseTestSeed("0x1F055EED", v));
  EXPECT_EQ(0x1F055EEDull, v);
  EXPECT_TRUE(laige::testing::ParseTestSeed("520445677", v));  // decimal form
  EXPECT_EQ(0x1F055EEDull, v);
  EXPECT_FALSE(laige::testing::ParseTestSeed("", v));
  EXPECT_FALSE(laige::testing::ParseTestSeed("0x", v));
  EXPECT_FALSE(laige::testing::ParseTestSeed("1F055EED", v));  // no 0x prefix
  EXPECT_FALSE(laige::testing::ParseTestSeed("0x1F055EEDx", v));  // trailing junk
  EXPECT_FALSE(laige::testing::ParseTestSeed("-1", v));  // negative
}

// Substream isolation sanity: two distinct substream ids of the same seed
// produce distinct streams (a collision would mean the derivation hash
// broke; the committed KATs above are the positive proof of determinism).
TEST(SeededRandom, DistinctSubstreamsDiverge) {
  u64 a[64] = {};
  u64 b[64] = {};
  laige::Prng ra =
      laige::Prng::deriveSubstream(laige::testing::kDefaultTestSeed,
                                   kSeedCheckStreamId);
  laige::Prng rb =
      laige::Prng::deriveSubstream(laige::testing::kDefaultTestSeed,
                                   kOverrideStreamId);
  for (int i = 0; i < 64; ++i) {
    a[i] = ra.next_u64();
    b[i] = rb.next_u64();
  }
  EXPECT_NE(fnv1a64(a, 64), fnv1a64(b, 64))
      << "substreams 1 and 2 of the default seed produced identical "
         "streams — the substream derivation is broken";
}
