// laige-core deterministic PRNG suite (M0-CORE-06).
//
// Step Verify scope (roadmap/M0-foundations.md):
//   - `ctest -R prng` green (suites: PrngGolden, PrngRange, PrngFloat01,
//     PrngSubstreams, PrngPeriod)
//   - Golden vectors: fixed seed -> committed first-N outputs and a
//     FNV-1a state hash, identical across builds. They are *intentionally*
//     expected to fail if the algorithm changes — the algorithm is part
//     of the determinism contract (ARCH-010), not an implementation detail.
//   - Transcription check against an independent inlined reference
//     (10^4 steps, PrngGolden.ReferenceMatch).
//   - Substream independence sanity (PrngSubstreams).
//   - Period: every nonzero state has period exactly 2^128 - 1 — proven,
//     not sampled: the PrngPeriod suite reconstructs the state map's
//     characteristic polynomial over GF(2) from a probe orbit
//     (Berlekamp-Massey) and checks irreducibility and primitivity
//     directly (CPP-014: method in the comments at each stage); plus an
//     empirical short-cycle screen of the output stream.
//
// House conventions: float checks go through double (exact dyadic
// oracles, -Wfloat-equal); named constants throughout (CORE-005); the
// GF(2) proof machinery below is self-contained and portable (no
// __int128, no compiler builtins — the same MSVC-compatibility scope the
// engine policy enforces). All KAT constants below were generated by a
// throwaway verification harness that cross-checked every primitive
// against independent oracles before being committed here.

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <iterator>
#include <vector>

#include "gtest/gtest.h"
#include "laige/prng.h"

// ---------------------------------------------------------------------------
// NFR-8.10 policy self-checks (compile-time; a violation fails the build)
// ---------------------------------------------------------------------------

#if defined(__cpp_exceptions)
static_assert(false,
              "prng_tests must be built with exceptions disabled "
              "(NFR-8.10); see laige_apply_engine_policy().");
#elif defined(__EXCEPTIONS) && __EXCEPTIONS
static_assert(false,
              "prng_tests must be built with exceptions disabled "
              "(NFR-8.10); see laige_apply_engine_policy().");
#endif

#if defined(__cpp_rtti) && __cpp_rtti
static_assert(false,
              "prng_tests must be built with RTTI disabled "
              "(NFR-8.10); see laige_apply_engine_policy().");
#endif

namespace {

using u32 = std::uint32_t;
using u64 = std::uint64_t;

// The committed golden seed (PRD §10.3: a stable, documented replay seed).
constexpr u64 kGoldenSeed = 0x1234567890ABCDEFull;

// First 32 master-stream draws of kGoldenSeed (KAT). Generated by the
// verified scratch harness; a change here means the algorithm changed.
constexpr u64 kGoldenFirst32[32] = {
    0x6C6322B836E9CA2Aull, 0x80CBB0CE4F5F5B15ull, 0xC1C40F25ED01D33Bull,
    0xD9AE3642D165A892ull,  0x6B9E1933B9450E57ull, 0xB295E905D583CBCAull,
    0xBCCA4B307DA5925Cull,  0x827F8AB112661918ull, 0x2D5B2E5A9821AC1Dull,
    0xFE41F6914E614056ull,  0xA4C21C20B4ACAC77ull, 0x4C7A4768855CCA10ull,
    0xB3B1C9087E3170A7ull,  0x3993FEFE85368C6Aull, 0x044A154B06CA10AEull,
    0x4840062518FBC6A6ull,  0x11F456D973C3895Eull, 0xDD0E5F357F818FC4ull,
    0x2EB7495EDCA97CE9ull,  0xDA0C5BB2597BD169ull, 0x7E0F4238E966D9C9ull,
    0xCA067BBBBB8E3628ull,  0x9EBC93FD6DF67747ull, 0xB4EA2D90D9F27354ull,
    0x17FD44EA429F0DEFull,  0x4B40FBEBDE074A29ull, 0xA96071BCCEB8E535ull,
    0x5A02B371B9238BDDull,  0x8EA2A2E5F42B5CC7ull, 0xDDF01B4B59F0C3CDull,
    0x9E7597D094D3030Bull,  0x574A691C461E06FEull,
};

// First master-stream draw of substream id of kGoldenSeed, id 0..7 (KAT).
constexpr u64 kSubstreamFirst[8] = {
    0x6C6322B836E9CA2Aull, 0x7CFF34A370249EC4ull, 0xE486F33C42EB03B8ull,
    0x50A8E8673127AD76ull, 0x2239DB320458242Dull, 0xE9CBBCC11E178E69ull,
    0x1CED7136F1BF5FC4ull, 0xEB23C2C7B799A9AEull,
};

// FNV-1a 64-bit, big-endian byte order per u64 (endianness-independent),
// the same convention as the fpx16_16 determinism KAT (math_fixed_tests).
u64 fnv1a64(const u64* values, std::size_t n) {
  u64 h = 0xcbf29ce484222325ull;  // FNV offset basis (named: FNV-1a spec)
  for (std::size_t i = 0; i < n; ++i) {
    for (int shift = 56; shift >= 0; shift -= 8) {
      h ^= (values[i] >> shift) & 0xFFull;
      h *= 0x100000001b3ull;  // FNV prime (named: FNV-1a spec)
    }
  }
  return h;
}

// ---------------------------------------------------------------------------
// Independent reference (lemire/SIMDxorshift, xorshift128plus.c), inlined
// for the transcription check: the SAME algorithm written with the
// reference's own variable structure, so any drift in Prng::next_u64 or
// Prng::stepState shows up within a few steps.
// ---------------------------------------------------------------------------

u64 refNext(u64& p1, u64& p2) {
  const u64 s1 = p1 ^ (p1 << 23);
  const u64 s0 = p2;
  p1 = s0;
  p2 = s1 ^ s0 ^ (s1 >> 18) ^ (s0 >> 5);
  return p2 + s0;
}

}  // namespace

// ---------------------------------------------------------------------------
// PrngGolden — committed KATs and the transcription check
// ---------------------------------------------------------------------------

TEST(PrngGolden, First32Match) {
  laige::Prng p(kGoldenSeed);
  for (int i = 0; i < 32; ++i) {
    EXPECT_EQ(p.next_u64(), kGoldenFirst32[i]) << "draw " << i;
  }
}

TEST(PrngGolden, FNV1aOfFirst4096) {
  laige::Prng p(kGoldenSeed);
  std::vector<u64> draws(4096);
  for (auto& d : draws) d = p.next_u64();
  // State hash of the first 4096 draws: the replay fixture (ARCH-010,
  // TEST-004). Fails if the algorithm changes — intentionally.
  EXPECT_EQ(fnv1a64(draws.data(), draws.size()), 0xB64E76173859B6D8ull);
}

TEST(PrngGolden, ReferenceMatch) {
  // Transcription check (10^4 consecutive outputs) against the inlined
  // reference, from a non-golden state so the KATs above cannot mask a
  // drift. The engine's output tap is the new second state word plus the
  // old second state word; the reference computes the same quantity in
  // its own variable structure.
  u64 e0 = 0xA5A5A5A5A5A5A5A5ull, e1 = 0x5A5A5A5A5A5A5A5Aull;
  u64 r0 = e0, r1 = e1;
  for (int i = 0; i < 10000; ++i) {
    const u64 refOut = refNext(r0, r1);
    const u64 old1 = e1;
    laige::Prng::stepState(e0, e1);
    const u64 engOut = e1 + old1;
    EXPECT_EQ(refOut, engOut) << "step " << i;
    EXPECT_EQ(r0, e0) << "step " << i;
    EXPECT_EQ(r1, e1) << "step " << i;
  }
}

TEST(PrngGolden, SeedStateNeverZero) {
  // splitmix64 is a bijection and its two seeding inputs differ by the
  // nonzero increment, so no seed reaches the excluded all-zero state.
  // Spot-check the first 100k seeds (fast; the proof is in the header).
  for (u64 seed = 0; seed < 100000; ++seed) {
    u64 s0 = 0, s1 = 0;
    laige::Prng::seedState(seed, s0, s1);
    EXPECT_TRUE(s0 != 0 || s1 != 0) << "seed " << seed;
  }
}

// ---------------------------------------------------------------------------
// PrngRange — Lemire unbiased reduction
// ---------------------------------------------------------------------------

TEST(PrngRange, KnownValues) {
  // Each draw starts a fresh golden-seed stream (independent KATs).
  auto draw = [](u32 lo, u32 hi) {
    laige::Prng p(kGoldenSeed);
    return p.next_range(lo, hi);
  };
  EXPECT_EQ(draw(5, 9), 7u);
  EXPECT_EQ(draw(0, 7), 3u);
  EXPECT_EQ(draw(0, 1), 0u);
  EXPECT_EQ(draw(1000000, 2000000), 1190186u);
}

TEST(PrngRange, PowerOfTwoSpanUsesFastPath) {
  // n = 8 divides 2^64, so the result is exactly the low 3 bits of the
  // first draw — the rem == 0 branch, verified against the KAT.
  u64 first = 0;
  {
    laige::Prng p(kGoldenSeed);
    first = p.next_u64();
  }
  laige::Prng p(kGoldenSeed);
  EXPECT_EQ(p.next_range(0, 8), static_cast<u32>(first & 7u));
}

TEST(PrngRange, SpanOneAlwaysLow) {
  laige::Prng p(kGoldenSeed);
  for (int i = 0; i < 1000; ++i) {
    EXPECT_EQ(p.next_range(0xFFFFFFFEu, 0xFFFFFFFFu), 0xFFFFFFFEu);
    EXPECT_EQ(p.next_range(0u, 1u), 0u);
  }
}

TEST(PrngRange, DrawsStayInBounds) {
  laige::Prng p(kGoldenSeed);
  const u32 spans[] = {1, 2, 3, 7, 8, 255, 256, 65535, 65536, 1000001,
                       0xFFFFFFFFu};
  for (u32 span : spans) {
    laige::Prng q(kGoldenSeed + span);
    for (int i = 0; i < 10000; ++i) {
      const u32 v = q.next_range(0, span);
      EXPECT_LT(v, span) << "span " << span << " draw " << i;
    }
  }
}

TEST(PrngRange, Unbiased) {
  // 2^18 draws; the Lemire rejection makes the distribution exactly
  // uniform, so every bucket lands at its expectation within ~12 sigma
  // (tolerances below are ~17 sigma: no flake possible in practice, and
  // the seed is fixed anyway — deterministic KAT either way).
  {
    laige::Prng p(kGoldenSeed);
    u64 counts[8] = {0, 0, 0, 0, 0, 0, 0, 0};
    const int n = 1 << 18;
    for (int i = 0; i < n; ++i) {
      const u32 v = p.next_range(0, 8);
      ++counts[v];
    }
    const u64 expected = n / 8;  // 16384, std ~ 120
    for (u32 v = 0; v < 8; ++v) {
      EXPECT_GT(counts[v], expected - 2000) << "bucket " << v;
      EXPECT_LT(counts[v], expected + 2000) << "bucket " << v;
    }
  }
  {
    laige::Prng p(kGoldenSeed);
    u64 counts[3] = {0, 0, 0};
    const int n = 1 << 18;
    for (int i = 0; i < n; ++i) {
      const u32 v = p.next_range(0, 3);
      ++counts[v];
    }
    // expected 87381.33 per bucket, std ~ 241; tolerance ~ 10 sigma.
    for (u32 v = 0; v < 3; ++v) {
      EXPECT_GT(counts[v], 87381u - 2500) << "bucket " << v;
      EXPECT_LT(counts[v], 87381u + 2500) << "bucket " << v;
    }
  }
}

// ---------------------------------------------------------------------------
// PrngFloat01 — exact 24-bit dyadic floats in [0, 1)
// ---------------------------------------------------------------------------

TEST(PrngFloat01, First8KnownValues) {
  // KAT: the first 8 draws of kGoldenSeed, as their 24-bit mantissa k of
  // k * 2^-24 (float equality goes through double; dyadic => exact).
  // 2^-24 is the exact inverse of laige::Prng::kFloat01Unit.
  const u64 ks[8] = {7103266ull, 8440752ull, 12698639ull, 14265910ull,
                     7052825ull, 11703785ull, 12372555ull, 8552330ull};
  laige::Prng p(kGoldenSeed);
  for (int i = 0; i < 8; ++i) {
    const double v = static_cast<double>(p.next_float01());
    EXPECT_EQ(v, static_cast<double>(ks[i]) * 0x1.0p-24) << "draw " << i;
  }
}

TEST(PrngFloat01, DyadicAndInBounds) {
  // 2^24: the inverse scale of kFloat01Unit (24 mantissa bits).
  constexpr double kScale24 = 16777216.0;
  laige::Prng p(kGoldenSeed);
  double sum = 0.0;
  const int n = 1 << 16;
  for (int i = 0; i < n; ++i) {
    const float f = p.next_float01();
    const double v = static_cast<double>(f);
    EXPECT_GE(v, 0.0) << "draw " << i;
    EXPECT_LT(v, 1.0) << "draw " << i;
    // Exactly k * 2^-24: v * 2^24 is an integer (v < 1 => v*2^24 < 2^24,
    // exactly representable in double).
    const double scaled = v * kScale24;
    EXPECT_EQ(scaled, std::floor(scaled)) << "draw " << i;
    sum += v;
  }
  // Mean of 2^16 draws: expected 0.5, std ~ 0.00356; tolerance ~ 14 sigma.
  EXPECT_GT(sum / n, 0.45);
  EXPECT_LT(sum / n, 0.55);
}

// ---------------------------------------------------------------------------
// PrngSubstreams — documented derivation and independence sanity
// ---------------------------------------------------------------------------

TEST(PrngSubstreams, FirstDrawsPerId) {
  for (u32 id = 0; id < 8; ++id) {
    laige::Prng sub = laige::Prng::deriveSubstream(kGoldenSeed, id);
    EXPECT_EQ(sub.next_u64(), kSubstreamFirst[id]) << "id " << id;
  }
}

TEST(PrngSubstreams, IdZeroIsMaster) {
  const laige::Prng master(kGoldenSeed);
  laige::Prng sub0 = master.substream(0);
  EXPECT_EQ(sub0.seed(), master.seed());
  for (int i = 0; i < 16; ++i) {
    EXPECT_EQ(sub0.next_u64(), kGoldenFirst32[i]) << "draw " << i;
  }
}

TEST(PrngSubstreams, DerivationComposes) {
  // derive(derive(seed, 1), 2) == derive(seed, 3): both by the seed
  // formula (id sum) and in produced output.
  const laige::Prng inner = laige::Prng::deriveSubstream(kGoldenSeed, 1);
  laige::Prng composed = inner.substream(2);
  laige::Prng direct = laige::Prng::deriveSubstream(kGoldenSeed, 3);
  EXPECT_EQ(composed.seed(), direct.seed());
  for (int i = 0; i < 16; ++i) {
    EXPECT_EQ(composed.next_u64(), direct.next_u64()) << "draw " << i;
  }
}

TEST(PrngSubstreams, SameIdIsDeterministic) {
  const laige::Prng a(kGoldenSeed);
  const laige::Prng b(kGoldenSeed);
  laige::Prng sa = a.substream(17);
  laige::Prng sb = b.substream(17);
  for (int i = 0; i < 64; ++i) {
    EXPECT_EQ(sa.next_u64(), sb.next_u64()) << "draw " << i;
  }
}

TEST(PrngSubstreams, StreamsDoNotOverlap) {
  // Independence sanity: 2^16 draws from two different substreams share
  // no value. (Both streams sit on the single period-2^128-1 state cycle,
  // but their 2^16-draw windows are separated by ~2^112 cycle positions —
  // overlap is impossible for these seeds; the check is a KAT guard
  // against derivation collapse.)
  std::vector<u64> a(1 << 16), b(1 << 16);
  {
    laige::Prng sa = laige::Prng::deriveSubstream(kGoldenSeed, 1);
    laige::Prng sb = laige::Prng::deriveSubstream(kGoldenSeed, 2);
    for (auto& v : a) v = sa.next_u64();
    for (auto& v : b) v = sb.next_u64();
  }
  std::sort(a.begin(), a.end());
  std::sort(b.begin(), b.end());
  std::vector<u64> overlap;
  std::set_intersection(a.begin(), a.end(), b.begin(), b.end(),
                        std::back_inserter(overlap));
  EXPECT_TRUE(overlap.empty());
}

// ---------------------------------------------------------------------------
// PrngPeriod — the period-2^128-1 proof and an output-stream screen
// ---------------------------------------------------------------------------

namespace period_proof {

using u32 = std::uint32_t;
using u64 = std::uint64_t;

// GF(2)[x] polynomials: degree <= 255 in four little-endian 64-bit words
// (bit i is the coefficient of x^i); 512-bit workspaces for products.
struct Poly {
  u64 w[4] = {0, 0, 0, 0};
};
struct Big {
  u64 w[8] = {0, 0, 0, 0, 0, 0, 0, 0};
};

bool polyBit(const Poly& p, int i) {
  return ((p.w[i / 64] >> (i % 64)) & 1) != 0;
}

bool polyZero(const Poly& p) {
  return p.w[0] == 0 && p.w[1] == 0 && p.w[2] == 0 && p.w[3] == 0;
}

int polyDeg(const Poly& p) {
  for (int deg = 255; deg >= 0; --deg) {
    if (polyBit(p, deg)) return deg;
  }
  return -1;
}

int bigDeg(const Big& a) {
  for (int deg = 511; deg >= 0; --deg) {
    if (((a.w[deg / 64] >> (deg % 64)) & 1) != 0) return deg;
  }
  return -1;
}

// a ^= m << k (m a 256-bit Poly, k >= 0, i + k < 512 for every set bit).
void bigShiftXor(Big& a, const Poly& m, int k) {
  for (int i = 0; i < 256; ++i) {
    if (!polyBit(m, i)) continue;
    const int j = i + k;
    assert(j < 512);  // invariant of the callers (see BM, polyMod)
    a.w[j / 64] ^= 1ull << (j % 64);
  }
}

// Carryless (GF(2)) product: XOR of (b << i) for each set bit i of a.
// Integer multiplication would be WRONG (carries are not GF(2) addition).
Big polyMul(const Poly& a, const Poly& b) {
  Big r;
  for (int i = 0; i < 256; ++i) {
    if (!polyBit(a, i)) continue;
    bigShiftXor(r, b, i);
  }
  return r;
}

// a (a Big, < 512 bits) reduced modulo m (a 256-bit Poly, m != 0):
// long division over GF(2) — XOR of m shifted into each excess degree.
Poly polyMod(Big a, const Poly& m) {
  const int d = polyDeg(m);
  assert(d >= 0);
  for (;;) {
    const int deg = bigDeg(a);
    if (deg < d) break;
    bigShiftXor(a, m, deg - d);
  }
  Poly r;
  r.w[0] = a.w[0];
  r.w[1] = a.w[1];
  r.w[2] = a.w[2];
  r.w[3] = a.w[3];
  return r;
}

Poly polyMulmod(const Poly& a, const Poly& b, const Poly& m) {
  return polyMod(polyMul(a, b), m);
}

// x^exp mod m, exp a 192-bit little-endian word array (squaring-and-
// multiplying; every intermediate is reduced mod m).
Poly polyPowX(const u64 exp[3], const Poly& m) {
  Poly result;
  result.w[0] = 1;  // x^0
  Poly base;
  base.w[0] = 2;  // x^1
  for (int i = 0; i < 192; ++i) {
    if (((exp[i / 64] >> (i % 64)) & 1) != 0) {
      result = polyMulmod(result, base, m);
    }
    base = polyMulmod(base, base, m);
  }
  return result;
}

Poly polyGcd(Poly a, Poly b) {
  while (!polyZero(b)) {
    Big ba;
    ba.w[0] = a.w[0];
    ba.w[1] = a.w[1];
    ba.w[2] = a.w[2];
    ba.w[3] = a.w[3];
    a = b;
    b = polyMod(ba, b);
  }
  return a;
}

// Berlekamp-Massey over GF(2) on the first `count` probe bits: returns the
// shortest connection polynomial C (C[0] = 1 form: the recurrence is
// s[n] = sum_{i=1..L} C[i] s[n-i], L = final length) and its length L.
// Standard BM (Berlekamp 1967; Massey 1969); invariant: after n+1 samples,
// L <= (n+1)/2 and m + L <= n + 1, so x^m B has degree <= n <= 511 and
// stays inside the 512-bit workspace.
Poly bm(const u64* s, int count, int& L) {
  Poly C, B, T;
  C.w[0] = 1;
  B.w[0] = 1;
  L = 0;
  int m = 1;
  for (int n = 0; n < count; ++n) {
    u64 d = s[n] & 1;
    for (int i = 1; i <= L; ++i) {
      if (polyBit(C, i) && ((s[n - i] & 1) != 0)) d ^= 1;
    }
    if (d == 0) {
      ++m;
      continue;
    }
    T = C;
    Big xb;  // x^m B
    for (int i = 0; i < 256; ++i) {
      if (!polyBit(B, i)) continue;
      const int j = i + m;
      assert(j < 512);
      xb.w[j / 64] ^= 1ull << (j % 64);
    }
    for (int w = 0; w < 4; ++w) C.w[w] ^= xb.w[w];
    for (int w = 4; w < 8; ++w) {
      if (xb.w[w] != 0) {
        std::abort();  // unreachable by the BM invariant; fail loudly
      }
    }
    if (2 * L <= n) {
      L = n + 1 - L;
      B = T;
      m = 1;
    } else {
      ++m;
    }
  }
  assert(L <= 256);
  return C;
}

// Portable 64x64 -> 128 multiply (32-bit limbs; verified against __int128
// in the scratch harness before committing).
struct U128 {
  u64 lo, hi;
};

U128 mul128(u64 a, u64 b) {
  const u32 a0 = (u32)a, a1 = (u32)(a >> 32);
  const u32 b0 = (u32)b, b1 = (u32)(b >> 32);
  const u64 c0 = (u64)a0 * b0;
  const u64 c1 = (u64)a0 * b1;
  const u64 c2 = (u64)a1 * b0;
  const u64 c3 = (u64)a1 * b1;
  const u64 mid = (c0 >> 32) + (c1 & 0xFFFFFFFFu) + (c2 & 0xFFFFFFFFu);
  return {(c0 & 0xFFFFFFFFu) | (mid << 32),
          c3 + (c1 >> 32) + (c2 >> 32) + (mid >> 32)};
}

// 128-bit / 64-bit division, binary long division (remainder ignored;
// used only where the dividend is an exact multiple).
U128 div128By64(u64 nhi, u64 nlo, u64 d) {
  u64 qhi = 0, qlo = 0, rhi = 0, rlo = 0;
  for (int i = 127; i >= 0; --i) {
    const u64 bit = (i < 64) ? ((nlo >> i) & 1) : ((nhi >> (i - 64)) & 1);
    rhi = (rhi << 1) | (rlo >> 63);
    rlo = (rlo << 1) | bit;
    if (rhi != 0 || rlo >= d) {
      if (rlo >= d) {
        rlo -= d;
      } else {
        rlo += (0u - d);
        --rhi;
      }
      if (i < 64) qlo |= (1ull << i);
      else qhi |= (1ull << (i - 64));
    }
  }
  return {qlo, qhi};
}

// Miller-Rabin, deterministic for n < 3.3e24 with the twelve fixed bases
// (all moduli here are < 2^36; add-mod stays below 2^64 since 2m < 2^64).
u64 addMod(u64 x, u64 y, u64 m) {
  const u64 s = x + y;
  return s >= m ? s - m : s;
}

u64 modmul(u64 a, u64 b, u64 m) {
  u64 r = 0;
  while (b) {
    if (b & 1) r = addMod(r, a, m);
    a = addMod(a, a, m);
    b >>= 1;
  }
  return r;
}

u64 modpow(u64 a, u64 e, u64 m) {
  u64 r = 1;
  while (e) {
    if (e & 1) r = modmul(r, a, m);
    a = modmul(a, a, m);
    e >>= 1;
  }
  return r;
}

bool isPrime64(u64 n) {
  if (n < 2) return false;
  for (u64 p : {2u, 3u, 5u, 7u, 11u, 13u, 17u, 19u, 23u, 29u, 31u, 37u}) {
    if (n % p == 0) return n == p;
  }
  u64 d = n - 1;
  int r = 0;
  while ((d & 1) == 0) {
    d >>= 1;
    ++r;
  }
  for (u64 a : {2u, 3u, 5u, 7u, 11u, 13u, 17u, 19u, 23u, 29u, 31u, 37u}) {
    u64 x = modpow(a, d, n);
    if (x == 1 || x == n - 1) continue;
    bool ok = false;
    for (int i = 0; i < r - 1; ++i) {
      x = modmul(x, x, n);
      if (x == n - 1) {
        ok = true;
        break;
      }
    }
    if (!ok) return false;
  }
  return true;
}

}  // namespace period_proof

namespace {

// One coordinate of the state map A on (part1, part2) (the engine's step,
// exposed via Prng::stepState), sampled once per step from a starting
// state. The probe bit is a fixed nonzero linear observation of the
// state (the top bit of word 2); any fixed nonzero coordinate works —
// the linear complexity of the orbit is the same for all of them.
void probeStateMap(u64* s0, u64* s1, int count, std::vector<u64>* probe) {
  probe->resize(count);
  for (int t = 0; t < count; ++t) {
    (*probe)[t] = (*s1 >> 63) & 1;
    laige::Prng::stepState(*s0, *s1);
  }
}

}  // namespace

// The committed period proof: the state map's characteristic polynomial
// over GF(2) is the primitive polynomial of degree 128, so every
// nonzero state has period exactly 2^128 - 1 (hence the output stream
// has no short cycle). Method (CPP-014):
//   1. Probe the map from the basis state e0 = (1, 0) — a length-512
//      bit sequence p[t] of one coordinate of A^t e0.
//   2. Berlekamp-Massey finds the shortest recurrence C of p. For a
//      sequence whose linear complexity is exactly 128, BM converges
//      after 2*128 = 256 samples (512 are used for margin); the
//      recurrence is then re-verified over the whole probe.
//   3. C (stored as sum c_i x^i, satisfying p[t] = sum c_i p[t-i]) is
//      the RECIPROCAL of the state map's characteristic polynomial:
//      charpoly(A)(x) = x^128 C(1/x) = sum c_{128-i} x^i =: P. (The
//      recurrence relates p[t] to LOWER indices; the characteristic
//      polynomial annihilates A, whose powers move to HIGHER indices.)
//   4. P(A) = 0 is checked directly on all 128 basis states (Cayley-
//      Hamilton in the form we need): P monic of degree 128 = dim and
//      P(A) = 0 imply P = charpoly(A).
//   5. P is checked irreducible: x^(2^128) = x (mod P) and
//      gcd(x^(2^d) - x, P) = 1 for every proper divisor d of 128
//      (Ruffini's theorem over GF(2)).
//   6. P is checked primitive: P | x^(2^128-1) - 1 and P does not divide
//      x^((2^128-1)/q) - 1 for every prime q | 2^128 - 1. Primitivity
//      of the characteristic polynomial of an invertible linear map over
//      GF(2) is exactly "every nonzero state has maximal period".
//   (Primitives: 2^128 - 1 = product of the nine primes below — verified
//    here by portable 128-bit multiply and by Miller-Rabin.)
TEST(PrngPeriod, StateMapHasPrimitiveCharacteristicPolynomial) {
  using period_proof::Poly;
  using period_proof::U128;
  using namespace period_proof;

  // 1. Probe.
  u64 s0 = 1, s1 = 0;
  std::vector<u64> probe;
  probeStateMap(&s0, &s1, 512, &probe);
  u64 probeBits = 0;
  for (u64 bit : probe) probeBits |= bit;
  ASSERT_NE(probeBits, 0u);  // the observation is nonzero somewhere

  // 2. BM.
  int L = 0;
  const Poly C = bm(probe.data(), 512, L);
  ASSERT_EQ(L, 128);
  ASSERT_EQ(polyDeg(C), 128);
  ASSERT_TRUE(polyBit(C, 0));  // monic in the connection form

  // The recurrence reproduces the probe beyond the BM window (256..512):
  // if BM had a bug, this fails before any polynomial claim is made.
  for (int t = 128; t < 512; ++t) {
    u64 acc = 0;
    for (int i = 1; i <= 128; ++i) {
      if (polyBit(C, i) && ((probe[t - i] & 1) != 0)) acc ^= 1;
    }
    ASSERT_EQ(acc, probe[t] & 1) << "t " << t;
  }

  // 3. P = x^128 C(1/x).
  Poly P;
  for (int i = 0; i <= 128; ++i) {
    if (!polyBit(C, i)) continue;
    const int j = 128 - i;
    P.w[j / 64] |= 1ull << (j % 64);
  }
  ASSERT_EQ(polyDeg(P), 128);
  ASSERT_TRUE(polyBit(P, 128));

  // 4. P(A) = 0 on every basis state: for e_j, accumulate
  //    sum_i P_i A^i e_j (XOR) and require the zero state.
  for (int j = 0; j < 128; ++j) {
    u64 t0 = (j < 64) ? (1ull << j) : 0;
    u64 t1 = (j >= 64) ? (1ull << (j - 64)) : 0;
    u64 acc0 = 0, acc1 = 0;
    for (int i = 0; i <= 128; ++i) {
      if (polyBit(P, i)) {
        acc0 ^= t0;
        acc1 ^= t1;
      }
      laige::Prng::stepState(t0, t1);
    }
    ASSERT_EQ(acc0, 0u) << "basis " << j;
    ASSERT_EQ(acc1, 0u) << "basis " << j;
  }

  // 5. Irreducibility (Ruffini): x^(2^128) = x (mod P) and
  //    gcd(x^(2^d) - x, P) = 1 for d in {1,2,4,8,16,32,64}.
  u64 exp128[3] = {0, 0, 1};  // 2^128
  const Poly x128 = polyPowX(exp128, P);
  Poly x;
  x.w[0] = 2;
  ASSERT_TRUE(x128.w[0] == x.w[0] && x128.w[1] == x.w[1] &&
              x128.w[2] == x.w[2] && x128.w[3] == x.w[3]);
  const int divisors[] = {1, 2, 4, 8, 16, 32, 64};
  for (int d : divisors) {
    u64 exp[3] = {0, 0, 0};
    if (d == 64) exp[1] = 1;
    else exp[0] = 1ull << d;
    Poly diff = polyPowX(exp, P);
    diff.w[0] ^= 2;  // x^(2^d) - x  (GF(2): - == +)
    Poly g = polyGcd(diff, P);
    Poly one;
    one.w[0] = 1;
    ASSERT_TRUE(g.w[0] == 1 && g.w[1] == 0 && g.w[2] == 0 && g.w[3] == 0)
        << "d " << d;
  }

  // 6. Primitivity: P | x^(2^128-1) - 1, and no shorter q-th root.
  //    2^128 - 1 = 3 * 5 * 17 * 257 * 641 * 65537 * 6700417 * 274177 *
  //                67280421310721  (Fermat-prime + Aurifeuillean factors).
  const u64 kPrimesOf2128m1[] = {
      3ull, 5ull, 17ull, 257ull, 641ull, 65537ull,
      6700417ull, 274177ull, 67280421310721ull,
  };
  for (u64 q : kPrimesOf2128m1) {
    ASSERT_TRUE(isPrime64(q)) << "factor " << q;
  }
  u64 plo = 1, phi = 0;  // 128-bit product accumulator
  for (u64 q : kPrimesOf2128m1) {
    const U128 m1 = mul128(plo, q);
    const U128 m2 = mul128(phi, q);
    plo = m1.lo;
    phi = m1.hi + m2.lo;
  }
  ASSERT_EQ(plo, 0xFFFFFFFFFFFFFFFFull);
  ASSERT_EQ(phi, 0xFFFFFFFFFFFFFFFFull);  // product == 2^128 - 1

  Poly one;
  one.w[0] = 1;
  u64 expFull[3] = {0xFFFFFFFFFFFFFFFFull, 0xFFFFFFFFFFFFFFFFull, 0};
  const Poly full = polyPowX(expFull, P);
  ASSERT_TRUE(full.w[0] == 1 && full.w[1] == 0 && full.w[2] == 0 &&
              full.w[3] == 0);
  for (u64 q : kPrimesOf2128m1) {
    const U128 e =
        div128By64(0xFFFFFFFFFFFFFFFFull, 0xFFFFFFFFFFFFFFFFull, q);
    u64 expE[3] = {e.lo, e.hi, 0};
    const Poly shortCyc = polyPowX(expE, P);
    // x^((2^128-1)/q) != 1 (mod P): a primitive polynomial is a
    // generator of GF(2^128)^*, so no proper divisor of 2^128-1 works.
    const bool isOne = shortCyc.w[0] == 1 && shortCyc.w[1] == 0 &&
                       shortCyc.w[2] == 0 && shortCyc.w[3] == 0;
    ASSERT_FALSE(isOne) << "q " << q;
  }
  // Every step of the proof passed: every nonzero state has period
  // exactly 2^128 - 1.
  SUCCEED();
}

// Empirical screen (complements the proof; cheap, and would catch a
// *construction* bug that the algebra could in principle miss): 4M draws
// have no duplicate, and no period-q pattern for the small prime divisors
// of 2^128 - 1.
TEST(PrngPeriod, OutputStreamHasNoShortCycles) {
  laige::Prng p(kGoldenSeed);
  std::vector<u64> v(4096000);
  for (auto& x : v) x = p.next_u64();
  {
    std::vector<u64> sorted(v);
    std::sort(sorted.begin(), sorted.end());
    u64 dups = 0;
    for (std::size_t i = 1; i < sorted.size(); ++i) {
      if (sorted[i] == sorted[i - 1]) ++dups;
    }
    EXPECT_EQ(dups, 0u);
  }
  // If the stream had period q, every window position would repeat.
  // Deterministic KAT: exactly 0 matches in a 4096-position window.
  const u64 primes[] = {3ull, 5ull, 17ull, 257ull, 641ull, 65537ull,
                        274177ull, 6700417ull};
  const int kW = 4096;
  for (u64 q : primes) {
    laige::Prng pre(kGoldenSeed);
    std::vector<u64> window(kW);
    for (auto& x : window) x = pre.next_u64();
    laige::Prng p2(kGoldenSeed);
    for (u64 i = 0; i < q; ++i) p2.next_u64();
    u64 matches = 0;
    for (int i = 0; i < kW; ++i) {
      if (p2.next_u64() == window[i]) ++matches;
    }
    EXPECT_EQ(matches, 0u) << "q " << q;
  }
}
